# Generated by Django 2.0.5 on 2018-05-20 19:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 20, 19, 46, 13, 981558, tzinfo=utc)),
        ),
    ]
