# Generated by Django 2.0.5 on 2018-05-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
